### ISSUE TITLE
Windows 11, install cuda fails

### ISSUE THREAD

**Issue by desfun** [drago87/TabbyAPI-Pinokio#1]
`(node:20264) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat 'C:\pinokio\api\TabbyAPI-Pinokio.git\install%20-%20NVIDIA%20Cuda%2012.x.js'`

After renaming "C:\pinokio\api\TabbyAPI-Pinokio.git\install - NVIDIA Cuda 12.x.js"  to 'C:\pinokio\api\TabbyAPI-Pinokio.git\install%20-%20NVIDIA%20Cuda%2012.x.js' 
it works.

Maybe sanitized or encodeURI paths at some point.

**Comment by drago87** [comment]
Have updated the code now. Had to rename the files to not use blank space.
If you have any more problems tell me.
